=== MarikoBot/hashi/hashi.config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "channels": {
      "type": "object",
      "title": "Channels",
      "description": "The channel ids for configuring the logger and other channel-based services.",
      "properties": {
        "status": {
          "type": "string",
          "title": "Status",
          "description": "The status channel id.",
          "minLength": 18,
          "maxLength": 20,
          "pattern": "[0-9]"
        }
      },
      "required": ["status"]
    },
    "database": {
      "type": "object",
      "title": "Database",
      "description": "The database configuration object (URI, database name, etc).",
      "properties": {
        "addressFamily": {
          "type": "string",
          "title": "TCP/IP Address Family",
          "description": "The database address family (4 for IPv4, 6 for IPv6)",
          "enum": ["IPv4", "IPv6"]
        },
        "connectionURI": {
          "type": "string",
          "title": "Database Connection URI",
          "description": "The database URI where the database is located.",
          "format": "uri"
        },
        "databaseName": {
          "type": "string",
          "title": "Database Name",
          "description": "The database name to connect/create for the project.",
          "pattern": "^[a-zA-Z_0-9][a-zA-Z0-9_ -]{2,62}[a-zA-Z_0-9]$"
        }
      },
      "required": ["addressFamily", "connectionURI", "databaseName"]
    },
    "defaultFeatures": {
      "type": "array",
      "title": "Default Features",
      "description": "The default features to add to the bot.",
      "items": {
        "type": "string",
        "enum": ["Command:help", "Command:ping", "Event:commands"],
        "description": "The default features to add to the bot."
      },
      "minItems": 0,
      "maxItems": 3
    },
    "envPath": {
      "type": "string",
      "title": "Env File",
      "description": "The environment variables file relative path.",
      "minLength": 6,
      "maxLength": 16
    },
    "intents": {
      "oneOf": [
        {
          "type": "integer",
          "title": "Client Intents",
          "description": "The client intents for the Discord Client instance.",
          "minimum": 0,
          "maximum": 3276799
        },
        {
          "type": "string",
          "title": "Client Intents",
          "description": "The client intents for the Discord Client instance.",
          "pattern": "[0-9]"
        }
      ]
    },
    "projectName": {
      "type": "string",
      "title": "Project Name",
      "description": "The name of the project (used into the logger).",
      "pattern": "^[a-zA-Z_0-9][a-zA-Z0-9_ -]{2,62}[a-zA-Z_0-9]$",
      "minLength": 3,
      "maxLength": 18
    }
  },
  "required": ["channels", "database", "defaultFeatures", "envPath", "intents", "projectName"]
}

=== MarikoBot/hashi/lab/hashi.config.json
{
  "$schema": "../hashi.config.schema.json",
  "channels": {
    "status": "1228631187459670046"
  },
  "intents": 0,
  "database": {
    "addressFamily": "IPv4",
    "connectionURI": "mongo://localhost:27017/",
    "databaseName": "hashi-plate"
  },
  "defaultFeatures": ["Command:help", "Command:ping", "Event:commands"],
  "envPath": "./.env",
  "projectName": "MarikoBot-Hashi"
}
